apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  PHX_HOST: {{ .Values.configmap.host }}
  DATABASE_HOST: {{ .Values.configmap.postgres.host }}
  DATABASE_NAME: {{ .Values.configmap.postgres.name }}
