name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update tag in manifest.yml
        run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}

  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/preparingforexams/papyrus-api:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/preparingforexams/papyrus-api:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
    needs: [ build_push_docker, lint ]
    steps:
      - uses: actions/checkout@v4
      - run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - run: sed -i -e "s#__SECRET_KEY_BASE__#${{ secrets.SECRET_KEY_BASE }}#g" values.yaml
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade papyrus-api . --install --namespace=papyrus --atomic
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
